# Use root/example as user/password credentials
version: '3.1'

services:

  mongodb_migrate:
    image: mongo:4
    
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: profectum
    ports:
      - '27017:27017'

   # Replica Set (required for Prisma Client)
  mongo:
    build: ./backend/mongodb_rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: profectum
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27018
    ports:
      - '27018:27018'